// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gosom/scrapemate (interfaces: HTTPFetcher)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock_http_fetcher.go -package=mock . HTTPFetcher
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	scrapemate "github.com/gosom/scrapemate"
	gomock "go.uber.org/mock/gomock"
)

// MockHTTPFetcher is a mock of HTTPFetcher interface.
type MockHTTPFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockHTTPFetcherMockRecorder
}

// MockHTTPFetcherMockRecorder is the mock recorder for MockHTTPFetcher.
type MockHTTPFetcherMockRecorder struct {
	mock *MockHTTPFetcher
}

// NewMockHTTPFetcher creates a new mock instance.
func NewMockHTTPFetcher(ctrl *gomock.Controller) *MockHTTPFetcher {
	mock := &MockHTTPFetcher{ctrl: ctrl}
	mock.recorder = &MockHTTPFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHTTPFetcher) EXPECT() *MockHTTPFetcherMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockHTTPFetcher) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockHTTPFetcherMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockHTTPFetcher)(nil).Close))
}

// Fetch mocks base method.
func (m *MockHTTPFetcher) Fetch(arg0 context.Context, arg1 scrapemate.IJob) scrapemate.Response {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fetch", arg0, arg1)
	ret0, _ := ret[0].(scrapemate.Response)
	return ret0
}

// Fetch indicates an expected call of Fetch.
func (mr *MockHTTPFetcherMockRecorder) Fetch(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockHTTPFetcher)(nil).Fetch), arg0, arg1)
}
